<a href="https://colab.research.google.com/github/Oleksii-Adamov/university-models-of-intelligent-systems/blob/main/MIS_lab2_var1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import random

# Завдання 1

In [13]:
def rand_list(size):
    return [random.randint(0, 99) for i in range(0, size)]

## Вправа 1.
Вводиться число n. Вивести масив розміру n×n, в
якому по діагоналі йдуть числа від 1 до n, а інші числа дорівнюють 0.

In [2]:
def task1_numpy(n):
    a = np.zeros((n, n))
    values = np.arange(1, n+1)
    np.fill_diagonal(a, values)
    return a

In [3]:
def task1_loop(n):
    a = np.zeros((n, n))
    values = np.arange(1, n+1)
    for i in range (0, n):
        a[i, i] = values[i]
    return a

In [4]:
def task1_loop_non_numpy(n):
    return [[0 if i != j else i+1 for j in range (0, n)] for i in range(0, n)]

In [5]:
%%timeit
ans = task1_numpy(100)

10.4 µs ± 2.25 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
ans = task1_numpy(5)
print(ans)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [7]:
%%timeit
task1_loop(100)

38 µs ± 1.24 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [8]:
ans = task1_loop(5)
print(ans)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [9]:
%%timeit
task1_loop_non_numpy(100)

581 µs ± 11.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [10]:
ans = task1_loop_non_numpy(5)
print(ans)

[[1, 0, 0, 0, 0], [0, 2, 0, 0, 0], [0, 0, 3, 0, 0], [0, 0, 0, 4, 0], [0, 0, 0, 0, 5]]


## Вправа 6.
З клавіатури вводиться масив. Замінити всі ненульові
елементи на –1.

In [11]:
def task6_numpy(a):
    arr = np.array(a)
    arr[arr != 0] = -1
    return arr

In [12]:
def task6_no_numpy(a):
    return [-1 if val != 0 else 0 for val in a]

In [14]:
%%timeit
task6_numpy(rand_list(100))

114 µs ± 42.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [15]:
task6_numpy([3, 4, 0, 9, 7, 0, 6, 0, 4, 0, 3])

array([-1, -1,  0, -1, -1,  0, -1,  0, -1,  0, -1])

In [16]:
%%timeit
task6_no_numpy(rand_list(100))

85.9 µs ± 705 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [17]:
task6_no_numpy([3, 4, 0, 9, 7, 0, 6, 0, 4, 0, 3])

[-1, -1, 0, -1, -1, 0, -1, 0, -1, 0, -1]

## Вправа 7.
З клавіатури вводиться масив. Замінити всі нульові
елементи на –1.

In [18]:
def task7_numpy(a):
    arr = np.array(a)
    arr[arr == 0] = -1
    return arr

In [19]:
def task7_no_numpy(a):
    return [-1 if val == 0 else val for val in a]

In [20]:
%%timeit
task7_numpy(rand_list(100))

109 µs ± 26 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [21]:
task7_numpy([3, 4, 0, 6, 5, 0, 3, 0, 4])

array([ 3,  4, -1,  6,  5, -1,  3, -1,  4])

In [22]:
%%timeit
task7_no_numpy(rand_list(100))

87.7 µs ± 10.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [23]:
task7_no_numpy([3, 4, 0, 6, 5, 0, 3, 0, 4])

[3, 4, -1, 6, 5, -1, 3, -1, 4]

## Вправа 9.
Вводиться число n. Створити масив значень від n до 0.

In [24]:
def task9_numpy(n):
    return np.arange(n, -1, -1)

In [25]:
def task9_no_numpy(n):
    return [i for i in range(n, -1, -1)]

In [26]:
%%timeit
task9_numpy(100)

966 ns ± 10.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [28]:
task9_numpy(10)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [27]:
%%timeit
task9_no_numpy(100)

4.51 µs ± 1.36 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [29]:
task9_no_numpy(10)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

## Вправа 10.
Вводиться числа n i m. Створити масив випадкових
значень n×m і обчислити мінімальне, максимальне значення, середнє та
середньо квадратичне відхилення, округлене до 3 знаків після коми.

In [30]:
def task10_numpy(n, m):
    a = np.random.rand(n,m)
    #print(a)
    return np.round(np.min(a), 3), np.round(np.max(a), 3), np.round(np.mean(a), 3), np.round(np.var(a, ddof=1), 3)

In [31]:
def task10_no_numpy(n, m):
    a = [[random.random() for j in range (0, m)] for i in range(0, n)]
    # print(a)
    size = n * m
    sum = 0
    min_val = a[0][0]
    max_val = a[0][0]
    for row in a:
        for val in row:
            sum += val
            min_val = min(min_val, val)
            max_val = max(max_val, val)
    mean_val = sum / size
    var_val = 0
    for row in a:
        for val in row:
            var_val += (val - mean_val) ** 2
    var_val = var_val / (size - 1)
    return round(min_val, 3), round(max_val, 3), round(mean_val, 3), round(var_val, 3)

In [36]:
%%timeit
task10_numpy(100, 100)

377 µs ± 89.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [32]:
task10_numpy(3, 2)

(0.081, 0.973, 0.585, 0.146)

In [37]:
%%timeit
task10_no_numpy(100, 100)

5.32 ms ± 94 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [33]:
task10_numpy(3, 2)

(0.108, 0.965, 0.557, 0.113)

## Вправа 11.
Створити масив одиниць розміром n×n та додати до
нього «рамку», що утворюється з 0.

In [ ]:
def task11_numpy(n):
    a = np.full((n,n), 1)
    return np.pad(a, 1)

In [ ]:
def task11_no_numpy(n):
    a = [[1 for j in range (0, n)] for i in range(0, n)]
    padded = [[a[i][j-1] if j != 0 and j != n + 1 else 0 for j in range (0, n+2)] for i in range(0, n)]
    padded = [[0] * (n+2)] + padded + [[0] * (n+2)]
    return padded

In [ ]:
%%timeit
task11_numpy(100)

54.8 µs ± 12.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
task11_numpy(4)

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0]])

In [ ]:
%%timeit
task11_no_numpy(100)

2.19 ms ± 399 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
task11_no_numpy(4)

[[0, 0, 0, 0, 0, 0],
 [0, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 0],
 [0, 0, 0, 0, 0, 0]]

## Вправа 15.
Заповнити парні стовпчикі матриці розміром n×n одиницями, а непарні – нулями.

In [ ]:
def task15_numpy(n):
    return np.fromfunction(lambda i, j: j % 2, (n, n))

In [ ]:
def task15_no_numpy(n):
    return [[j % 2 for j in range (0, n)] for i in range(0, n)]

In [ ]:
%%timeit
task15_numpy(100)

NameError: name 'task15_numpy' is not defined

In [ ]:
task15_numpy(5)

array([[0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0.]])

In [ ]:
%%timeit
task15_no_numpy(100)

578 µs ± 7.87 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
task15_no_numpy(5)

[[0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0]]

# Вправа 17.
Заповнити вектор значеннями від 0 до n. Замінити
знаки для всіх значень, що менші за $n/2$ та більші за $3n/4$ на
протилежні.

In [ ]:
def task17_numpy(n):
    a = np.arange(n)
    cond = np.logical_or(a < n / 2, a > 3*n/4)
    return np.where(cond, -a, a)

In [ ]:
def task17_no_numpy(n):
    a = [i for i in range(0, n)]
    return [-val if val < n / 2 or val > 3*n/4 else val for val in a]

In [ ]:
%%timeit
task17_numpy(100)

7.68 µs ± 166 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
task17_numpy(10)

array([ 0, -1, -2, -3, -4,  5,  6,  7, -8, -9])

In [ ]:
%%timeit
task17_no_numpy(100)

21.4 µs ± 681 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
task17_no_numpy(10)

[0, -1, -2, -3, -4, 5, 6, 7, -8, -9]

# Вправа 18.
Згенерувати вектор з n випадкових чисел в діапазоні
від 0 до 99. Визначити кількість унікальних чисел в послідовності.

In [ ]:
def task18_numpy(n):
    a = np.random.randint(0, 100, n)
    return np.unique(a).shape[0]

In [ ]:
def task18_no_numpy(n):
    a = [random.randint(0, 99) for i in range(0, n)]
    print(a)
    d = {}
    for val in a:
        d[val] = True
    return len(d)

In [ ]:
%%timeit
task18_numpy(100)

In [ ]:
task18_numpy(10)

[49 80 90 50 13 62 94 68 27 27]


9

In [ ]:
%%timeit
task18_no_numpy(100)

In [ ]:
task18_no_numpy(10)

[34, 62, 79, 77, 62, 46, 57, 87, 77, 33]


8

# Завдання 2

Розв’язати систему алгебраїчних рівнянь за допомогою
формул Крамера і виконати перевірку за допомогою:

    a. матричного множення;
    b. оберненої матриці;
    c. функції numpy.linalg.solve().
Порівняти всі рішення за допомогою функції numpy.allclose().
\begin{align}
\left\{
\begin{array}{l}
x_1+x_2+2x_3+3x_4=1 \\
3x_1-x_2-x_3-2x_4=-4 \\
2x_1-3x_2-x_3-x_4=-6 \\
x_1+2x_2+3x_3-x_4=-4
\end{array}
\right.
\end{align}

In [47]:
def kramer_lin_eq_solve(A_input, b):
    A = np.copy(A_input)
    det_A = np.linalg.det(A)
    if abs(det_A) < 1e-9:
        return None
    n = A.shape[0]
    solution = np.empty(n)
    for i in range(0, n):
        original_column = np.copy(A[:, i])
        A[:, i] = b
        det_A_i = np.linalg.det(A)
        solution[i] = det_A_i / det_A
        A[:, i] = original_column
    return solution

In [48]:
A = np.array([[1, 1, 2, 3], [3, -1, -1, -2], [2, -3, -1, -1], [1, 2, 3, -1]])
b = np.array([1, -4, -6, -4])

In [50]:
kramer_sol = kramer_lin_eq_solve(A, b)
kramer_sol

array([-0.55555556,  1.88888889, -2.        ,  1.22222222])

In [51]:
b_from_sol = np.dot(A, kramer_sol)
print(b_from_sol)
np.allclose(b_from_sol, b)

[ 1. -4. -6. -4.]


True

In [52]:
sol_from_inv = np.linalg.inv(A) @ b
print(sol_from_inv)
np.allclose(kramer_sol, sol_from_inv)

[-0.55555556  1.88888889 -2.          1.22222222]


True

In [53]:
numpy_sol = np.linalg.solve(A, b)
print(numpy_sol)
np.allclose(kramer_sol, numpy_sol)

[-0.55555556  1.88888889 -2.          1.22222222]


True

# Завдання 3

Обчислити значення матричного виразу

    а. з використанням універсальних функцій бібліотеки NumPy.
    b. за допомогою ітеративних конструкцій (з використанням
    циклів, спискових включень тощо).
    с. для обох випадків підрахувати час виконання скрипту та
    зробити висновок.

Порівняти всі рішення за допомогою функції numpy.allclose().
$$2(A+B)(2B-A),$$ де \begin{align} A = \begin{pmatrix}
2 & 3 & -1 \\
4 & 5 & 2 \\
-1 & 0 & 7 \\
\end{pmatrix},
\end{align}
\begin{align} B = \begin{pmatrix}
-1 & 0 & 5 \\
0 & 1 & 3 \\
2 & -2 & 4 \\
\end{pmatrix}.
\end{align}

In [69]:
def add_matricies(A, B):
    if (A.shape != B.shape):
        return None
    return np.array([[A[i,j] + B[i,j] for j in range(0, A.shape[1])] for i in range(0, A.shape[0])])

In [70]:
def mult_matrix_by_scalar(A, c):
    return np.array([[A[i,j] * c for j in range(0, A.shape[1])] for i in range(0, A.shape[0])])

In [71]:
def mult_matricies(A, B):
    if (A.shape[1] != B.shape[0]):
        return None
    ans = np.array([[0 for j in range(0, B.shape[1])] for i in range(0, A.shape[0])])
    for i in range(0, A.shape[0]):
        for j in range(0, B.shape[1]):
            for k in range(0, A.shape[1]):
                ans[i, j] += A[i, k] * B[k, j]
    return ans

In [72]:
A = np.array([[2, 3, -1], [4, 5, 2], [-1, 0, 7]])
B = np.array([[-1, 0, 5], [0, 1, 3], [2, -2, 4]])

In [73]:
numpy_ans = 2 * (A + B) @ (2*B - A)
print(numpy_ans)

[[   8  -56   54]
 [ -30 -100  146]
 [ 118  -82   28]]


In [74]:
loop_ans = mult_matrix_by_scalar(mult_matricies(add_matricies(A, B), add_matricies(mult_matrix_by_scalar(B, 2), mult_matrix_by_scalar(A, -1))), 2)
print(loop_ans)

[[   8  -56   54]
 [ -30 -100  146]
 [ 118  -82   28]]


In [75]:
np.allclose(numpy_ans, loop_ans)

True

In [76]:
%%timeit
numpy_ans = 2 * (A + B) @ (2*B - A)

7.87 µs ± 3.18 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [77]:
%%timeit
loop_ans = mult_matrix_by_scalar(mult_matricies(add_matricies(A, B), add_matricies(mult_matrix_by_scalar(B, 2), mult_matrix_by_scalar(A, -1))), 2)

60.2 µs ± 723 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
